# Generated by Django 4.0.2 on 2022-02-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ok'), (2, 'fine'), (3, 'good'), (4, 'amazing'), (5, 'incredible')], null=True),
        ),
    ]
